CREATE TABLE IF NOT EXISTS pokemons(
    Id SERIAL PRIMARY KEY,
    TrainerID VARCHAR(255) NOT NULL DEFAULT ' ',
    Name VARCHAR(255) NOT NULL DEFAULT ' ',
    HasBadge boolean NOT NULL DEFAULT FALSE
);
