// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: protos/pokemon.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePokemonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrainerId string `protobuf:"bytes,1,opt,name=trainer_id,json=trainerId,proto3" json:"trainer_id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	HasBadge  bool   `protobuf:"varint,3,opt,name=has_badge,json=hasBadge,proto3" json:"has_badge,omitempty"`
}

func (x *CreatePokemonRequest) Reset() {
	*x = CreatePokemonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pokemon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePokemonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePokemonRequest) ProtoMessage() {}

func (x *CreatePokemonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pokemon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePokemonRequest.ProtoReflect.Descriptor instead.
func (*CreatePokemonRequest) Descriptor() ([]byte, []int) {
	return file_protos_pokemon_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePokemonRequest) GetTrainerId() string {
	if x != nil {
		return x.TrainerId
	}
	return ""
}

func (x *CreatePokemonRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePokemonRequest) GetHasBadge() bool {
	if x != nil {
		return x.HasBadge
	}
	return false
}

type CreatePokemonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreatePokemonResponse) Reset() {
	*x = CreatePokemonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pokemon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePokemonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePokemonResponse) ProtoMessage() {}

func (x *CreatePokemonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pokemon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePokemonResponse.ProtoReflect.Descriptor instead.
func (*CreatePokemonResponse) Descriptor() ([]byte, []int) {
	return file_protos_pokemon_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePokemonResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAllFromOneTrainerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrainerId string `protobuf:"bytes,1,opt,name=trainer_id,json=trainerId,proto3" json:"trainer_id,omitempty"`
}

func (x *GetAllFromOneTrainerRequest) Reset() {
	*x = GetAllFromOneTrainerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pokemon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllFromOneTrainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFromOneTrainerRequest) ProtoMessage() {}

func (x *GetAllFromOneTrainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pokemon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFromOneTrainerRequest.ProtoReflect.Descriptor instead.
func (*GetAllFromOneTrainerRequest) Descriptor() ([]byte, []int) {
	return file_protos_pokemon_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllFromOneTrainerRequest) GetTrainerId() string {
	if x != nil {
		return x.TrainerId
	}
	return ""
}

type GetAllFromOneTrainerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pokelist []*UpdatePokemonRequest `protobuf:"bytes,1,rep,name=pokelist,proto3" json:"pokelist,omitempty"`
}

func (x *GetAllFromOneTrainerResponse) Reset() {
	*x = GetAllFromOneTrainerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pokemon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllFromOneTrainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFromOneTrainerResponse) ProtoMessage() {}

func (x *GetAllFromOneTrainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pokemon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFromOneTrainerResponse.ProtoReflect.Descriptor instead.
func (*GetAllFromOneTrainerResponse) Descriptor() ([]byte, []int) {
	return file_protos_pokemon_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllFromOneTrainerResponse) GetPokelist() []*UpdatePokemonRequest {
	if x != nil {
		return x.Pokelist
	}
	return nil
}

type UpdatePokemonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TrainerId string `protobuf:"bytes,2,opt,name=trainer_id,json=trainerId,proto3" json:"trainer_id,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	HasBadge  bool   `protobuf:"varint,4,opt,name=has_badge,json=hasBadge,proto3" json:"has_badge,omitempty"`
}

func (x *UpdatePokemonRequest) Reset() {
	*x = UpdatePokemonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pokemon_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePokemonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePokemonRequest) ProtoMessage() {}

func (x *UpdatePokemonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pokemon_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePokemonRequest.ProtoReflect.Descriptor instead.
func (*UpdatePokemonRequest) Descriptor() ([]byte, []int) {
	return file_protos_pokemon_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePokemonRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePokemonRequest) GetTrainerId() string {
	if x != nil {
		return x.TrainerId
	}
	return ""
}

func (x *UpdatePokemonRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePokemonRequest) GetHasBadge() bool {
	if x != nil {
		return x.HasBadge
	}
	return false
}

type UpdatePokemonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TrainerId string `protobuf:"bytes,2,opt,name=trainer_id,json=trainerId,proto3" json:"trainer_id,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	HasBadge  bool   `protobuf:"varint,4,opt,name=has_badge,json=hasBadge,proto3" json:"has_badge,omitempty"`
}

func (x *UpdatePokemonResponse) Reset() {
	*x = UpdatePokemonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pokemon_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePokemonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePokemonResponse) ProtoMessage() {}

func (x *UpdatePokemonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pokemon_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePokemonResponse.ProtoReflect.Descriptor instead.
func (*UpdatePokemonResponse) Descriptor() ([]byte, []int) {
	return file_protos_pokemon_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePokemonResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePokemonResponse) GetTrainerId() string {
	if x != nil {
		return x.TrainerId
	}
	return ""
}

func (x *UpdatePokemonResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePokemonResponse) GetHasBadge() bool {
	if x != nil {
		return x.HasBadge
	}
	return false
}

var File_protos_pokemon_proto protoreflect.FileDescriptor

var file_protos_pokemon_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0x66,
	0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x72, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x61, 0x73,
	0x5f, 0x62, 0x61, 0x64, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x68, 0x61,
	0x73, 0x42, 0x61, 0x64, 0x67, 0x65, 0x22, 0x27, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x3c, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x72, 0x6f, 0x6d, 0x4f, 0x6e, 0x65,
	0x54, 0x72, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x22, 0x58, 0x0a,
	0x1c, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x72, 0x6f, 0x6d, 0x4f, 0x6e, 0x65, 0x54, 0x72,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a,
	0x08, 0x70, 0x6f, 0x6b, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50,
	0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x08, 0x70,
	0x6f, 0x6b, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x76, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x61, 0x73, 0x5f, 0x62, 0x61, 0x64, 0x67, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x68, 0x61, 0x73, 0x42, 0x61, 0x64, 0x67, 0x65, 0x22,
	0x77, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x68,
	0x61, 0x73, 0x5f, 0x62, 0x61, 0x64, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x68, 0x61, 0x73, 0x42, 0x61, 0x64, 0x67, 0x65, 0x32, 0x84, 0x02, 0x0a, 0x0b, 0x50, 0x6f, 0x6b,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x63, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x72, 0x6f, 0x6d, 0x4f,
	0x6e, 0x65, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x72, 0x6f, 0x6d, 0x4f, 0x6e, 0x65,
	0x54, 0x72, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x72,
	0x6f, 0x6d, 0x4f, 0x6e, 0x65, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f,
	0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_pokemon_proto_rawDescOnce sync.Once
	file_protos_pokemon_proto_rawDescData = file_protos_pokemon_proto_rawDesc
)

func file_protos_pokemon_proto_rawDescGZIP() []byte {
	file_protos_pokemon_proto_rawDescOnce.Do(func() {
		file_protos_pokemon_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_pokemon_proto_rawDescData)
	})
	return file_protos_pokemon_proto_rawDescData
}

var file_protos_pokemon_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protos_pokemon_proto_goTypes = []interface{}{
	(*CreatePokemonRequest)(nil),         // 0: protos.CreatePokemonRequest
	(*CreatePokemonResponse)(nil),        // 1: protos.CreatePokemonResponse
	(*GetAllFromOneTrainerRequest)(nil),  // 2: protos.GetAllFromOneTrainerRequest
	(*GetAllFromOneTrainerResponse)(nil), // 3: protos.GetAllFromOneTrainerResponse
	(*UpdatePokemonRequest)(nil),         // 4: protos.UpdatePokemonRequest
	(*UpdatePokemonResponse)(nil),        // 5: protos.UpdatePokemonResponse
}
var file_protos_pokemon_proto_depIdxs = []int32{
	4, // 0: protos.GetAllFromOneTrainerResponse.pokelist:type_name -> protos.UpdatePokemonRequest
	0, // 1: protos.PokeService.Create:input_type -> protos.CreatePokemonRequest
	2, // 2: protos.PokeService.GetAllFromOneTrainer:input_type -> protos.GetAllFromOneTrainerRequest
	4, // 3: protos.PokeService.Update:input_type -> protos.UpdatePokemonRequest
	1, // 4: protos.PokeService.Create:output_type -> protos.CreatePokemonResponse
	3, // 5: protos.PokeService.GetAllFromOneTrainer:output_type -> protos.GetAllFromOneTrainerResponse
	5, // 6: protos.PokeService.Update:output_type -> protos.UpdatePokemonResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_pokemon_proto_init() }
func file_protos_pokemon_proto_init() {
	if File_protos_pokemon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_pokemon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePokemonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pokemon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePokemonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pokemon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllFromOneTrainerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pokemon_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllFromOneTrainerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pokemon_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePokemonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pokemon_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePokemonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_pokemon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_pokemon_proto_goTypes,
		DependencyIndexes: file_protos_pokemon_proto_depIdxs,
		MessageInfos:      file_protos_pokemon_proto_msgTypes,
	}.Build()
	File_protos_pokemon_proto = out.File
	file_protos_pokemon_proto_rawDesc = nil
	file_protos_pokemon_proto_goTypes = nil
	file_protos_pokemon_proto_depIdxs = nil
}
